version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  communication-control:
    build: .
    container_name: communication-control
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
